name: "Evolver"
description: "Self-evolving repo agent (Gemini)"
inputs:
  mode:
    description: "pr|push"
    required: false
    default: "pr"
  provider:
    description: "LLM provider (currently only: gemini)"
    required: false
    default: "gemini"
  model:
    description: "Model name"
    required: false
    default: "gemini-2.5-flash-lite"
  workdir:
    description: "Working directory"
    required: false
    default: "."
  repo_goal:
    description: "High-level goal"
    required: false
    default: ""
  commands:
    description: "Newline-separated verification commands"
    required: false
    default: ""
  allow_workflow_edits:
    description: "Allow .github/workflows edits"
    required: false
    default: "false"
  log_level:
    description: "Log level: debug|info|warn|error"
    required: false
    default: "info"
  log_format:
    description: "Log format: text|json"
    required: false
    default: "text"
  log_file:
    description: "Optional log file path"
    required: false
    default: ".evolver/evolver.log"
  github_token:
    description: "Optional GitHub token override (defaults to github.token)"
    required: false
    default: ""
  gemini_api_key:
    description: "Gemini API key (pass from secrets)"
    required: true

outputs:
  changed:
    description: "Whether repo changed"
    value: ${{ steps.evolver.outputs.changed }}
  summary:
    description: "Summary of changes"
    value: ${{ steps.evolver.outputs.summary }}
  pr_url:
    description: "Pull request URL when mode=pr"
    value: ${{ steps.evolver.outputs.pr_url }}

runs:
  using: "composite"
  steps:
    - name: "Checkout repository"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: "Set up Go"
      uses: actions/setup-go@v6
      with:
        go-version-file: ${{ github.action_path }}/go.mod
        cache: true

    - name: "Install evolver"
      shell: bash
      run: |
        set -euo pipefail
        bash "${{ github.action_path }}/dist/install.sh"

    - name: "Run evolver"
      id: evolver
      shell: bash
      run: |
        set -euo pipefail
        evolver
      env:
        EVOLVER_MODE: ${{ inputs.mode }}
        EVOLVER_PROVIDER: ${{ inputs.provider }}
        EVOLVER_MODEL: ${{ inputs.model }}
        EVOLVER_WORKDIR: ${{ inputs.workdir }}
        EVOLVER_REPO_GOAL: ${{ inputs.repo_goal }}
        EVOLVER_COMMANDS: ${{ inputs.commands }}
        EVOLVER_ALLOW_WORKFLOWS: ${{ inputs.allow_workflow_edits }}
        EVOLVER_LOG_LEVEL: ${{ inputs.log_level }}
        EVOLVER_LOG_FORMAT: ${{ inputs.log_format }}
        EVOLVER_LOG_FILE: ${{ inputs.log_file }}
        GITHUB_TOKEN: ${{ inputs.github_token != '' && inputs.github_token || github.token }}
        GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
